### PR TITLE
Ensuring that animations never lag in any Portal 2 mod

### PR DESCRIPTION
**Pull request by karl-police**
aaaaain't noo waaaay that this was it

``animateeveryframe=1``

😱 

damn

there may be some mods that initialize this value on 0 so 🤷 

what is that ``ctx`` thing even

### CODE REVIEW

**Comment by TeamSpen210** [comment]
There's a reason I don't set this, it makes props run their think function every frame and check all their animation swapping behaviour. That's pointlessly wasteful, the bug is in engine code in the mods you mention.

**Comment by karl-police** [comment]
> There's a reason I don't set this, it makes props run their think function every frame and check all their animation swapping behaviour. That's pointlessly wasteful, the bug is in engine code in the mods you mention.

apparently this isn't an issue in Portal 2

Does that mean Portal 2 has AnimateEveryFrame on by default?

**Comment by TeamSpen210** [comment]
It does not, the difference is that it doesn't do the clientside animation thing.

**Comment by karl-police** [comment]
> It does not, the difference is that it doesn't do the clientside animation thing.

I figured out ``m_bClientSideAnimation`` later, but we can't set it. We could set it if the mod or game has ``NetProps``.

**Pull request closed without merging**
